### ISSUE TITLE
Stuck on trying to port it to C++

### ISSUE THREAD

**Issue by rpgplayerrobin** [BorisTheBrave/chiseled-random-paths#1]
Hey! I saw the demo on your website and it looked awesome! I tried converting it to C++, but for some reason I never actually get any path. I have compared my code to yours for hours but I cannot see any difference... Do you think you might take a quick look on what can be wrong? :o

My C++ code is here: https://pastebin.com/59tXenZt

**Comment by BorisTheBrave** [comment]
I cannot debug C++ code just by reading it. 

I suggest you test the individual parts. Is findArticulationPoints working? What do you see if you stop the process early.
