### ISSUE TITLE
Array operator

### ISSUE THREAD

**Issue by HorjuRares** [BorisTheBrave/chiseled-random-paths#2]
https://github.com/BorisTheBrave/chiseled-random-paths/blob/c66da002ab6ecacf8a5e9aa0772e1a2081ce58c5/chisel.ts#L20

Hello!

I am new to typescript and I quite don't understand what does the array[i]?.[j] (?.) operator is used for.
I would be extremely grateful if someone could help me.

Thank you!

**Comment by BorisTheBrave** [comment]
Right, i forgot to write this code in a readable style.

`array?.[i]` is the same as `array[i]`. But it doesn't throw an error if array is null.

**Comment by HorjuRares** [comment]
Thank you very much!
